name: Gitleaks Scan

on:
  push:
    branches:
      - main

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup GitLeaks
        run: |
          curl -L -o gitleaks.tar.gz https://github.com/zricethezav/gitleaks/releases/latest/download/gitleaks-linux-amd64.tar.gz
          tar -xzf gitleaks.tar.gz
          chmod +x gitleaks

      - name: Scan for leaks
        run: |
          ./gitleaks --path=. --config=.gitleaks.toml

